db:
  username: "postgres"
  password: "qwerty"
  host: "host.docker.internal"
  port: "5435"
  dbname: "postgres"
  sslmode: "disable"

server:
  port: "8081"
  host: "localhost"
  env: "local"
  timeout: "10h"

mail:
  host: "smtp.gmail.com"
  port: "465"
